#!/bin/bash
# mysqldump_sep
#   Dumps each mysql-database on individual files and gzips it.
#   Gets from ~/.my.cnf myslq-user, password and mysqldump options.
#
# :Author:   Jordi Funollet <jordi.f@ati.es>


# TODO:
# - check_conf_file ()
# - broader pre_check

case $1 in
    '-u'|'--usage'|'-h'|'--help')
        cat <<.
Usage:  `basename $0` [DBNAME]...
Wraps 'mysqldump' to dump every db on a gzipped file.

With no DBNAMEs, dumps all databases.

Example configuration for ~/.my.cnf
    [client]
    user            = me
    password        = secret
    
    [mysqldump]
    opt
.
        exit 1
        ;;
esac


# Import commonly used functions.
if [ -f "$PWD/common-sh-functions" ] ; then
    . "$PWD/common-sh-functions"
elif [ -f /usr/local/bin/common-sh-functions ] ; then
    . /usr/local/bin/common-sh-functions
else
    echo "common-sh-functions not found"
    exit 1
fi


####  Custom config  ####
# Destination directory.
BACKUPDIR='/home/backups/mysql'
#########################


function pre_checks () {
    test_var BACKUPDIR
}    


function main () {
    umask 0077
    
    DDBB="$*"
    if [ -z "$DDBB" ] ; then
	# Backup all DBs.
        DDBB=`mysql -BN -e 'show databases;'`
    fi
    
    # Dump each database
    for db in $DDBB ; do
	FNAME="$BACKUPDIR/$db.`date +%F.%H%M%S`.mysql"
	mysqldump "$db" > "$FNAME" || warn "problems dumping $db"
	# Compress if has contents, warn else.
	[ -s "$FNAME" ] && gzip -f "$FNAME" || warn "$FNAME void."
    done

    exit 0
}


pre_checks
main
