#!/bin/bash
# mysqldump_sep
#   Dumps each mysql-database on individual files and gzips it.
#   Gets myslq-user and password from ~/.my.cnf.
#
# :Author:   Jordi Funollet <jordi.f@ati.es>


# TODO:
# - check_conf_file ()
# - broader pre_check

# Import commonly used functions.
if [ -f ./common-sh-functions ] ; then
    . ./common-sh-functions
elif [ -f /usr/local/bin/common-sh-functions ] ; then
    . /usr/local/bin/common-sh-functions
else
    echo "common-sh-functions not found"
    exit 1
fi


####  Custom config  ####
# Destination directory.
BACKUPDIR='/home/backups/mysql'
# Databases to backup. Left void to backup all dbs.
DDBB=''
#########################


function pre_checks () {
    test_var BACKUPDIR
}    


function main () {
    umask 0077
    
    if [ -z "$DDBB" ] ; then
	# Backup all DBs.
	DDBB=`mysqlshow | awk '{print $2}' | tail +4 `
    fi
    
    # Dump each database
    for db in $DDBB ; do
	FNAME="$BACKUPDIR/mysql.$db.`date +%F.%H%M%S`.mysql"
	mysqldump --opt "$db" > "$FNAME" || warn "problems dumping $db"
	# Compress if has contents, warn else.
	[ -s "$FNAME" ] && gzip -f "$FNAME" || warn "$FNAME void."
    done

    exit 0
}


pre_checks
main 